apiVersion: v1
kind: Namespace
metadata:
  name: circleguard-dev
  labels:
    env: dev
    project: circleguard
    name: circleguard-dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: circleguard-stage
  labels:
    env: stage
    project: circleguard
    name: circleguard-stage
---
apiVersion: v1
kind: Namespace
metadata:
  name: circleguard-prod
  labels:
    env: prod
    project: circleguard
    name: circleguard-prod
