apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-config.yaml
  - 10-databases.yaml
  - 20-kafka.yaml
  - 30-services.yaml
  - 40-observability.yaml

commonLabels:
  project: circleguard
