apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: circleguard-prod

resources:
  - ../base

commonLabels:
  env: prod

images:
  - { name: circleguard/auth,         newTag: prod }
  - { name: circleguard/identity,     newTag: prod }
  - { name: circleguard/gateway,      newTag: prod }
  - { name: circleguard/promotion,    newTag: prod }
  - { name: circleguard/notification, newTag: prod }
  - { name: circleguard/dashboard,    newTag: prod }

# En prod escalamos los servicios stateless a 2 réplicas.
patches:
  - target: { kind: Deployment, name: auth }
    patch: |-
      - { op: replace, path: /spec/replicas, value: 2 }
  - target: { kind: Deployment, name: gateway }
    patch: |-
      - { op: replace, path: /spec/replicas, value: 2 }
  - target: { kind: Deployment, name: dashboard }
    patch: |-
      - { op: replace, path: /spec/replicas, value: 2 }
